### PR TITLE
Feat/add user accessible data import

### PR DESCRIPTION
**Pull request by pdmnyberg**
This PR tries to implement feature #36

## To test
- `docker compose up`
- go to: http://localhost:8000
- sign in as any node
- go to the tab [Upload data](http://localhost:8000/upload-data)
- upload your data one file at a time
- go to the tab [Edit events](http://localhost:8000/event/list)
- verify that you can edit your events
- verify that the event stats properly reflects what you uploaded

## Test dataset
A test data set `test-data.zip` which contains three example files. One for each type. In order to make the test data set work in your environment you must first upload the events and then map the rows of each metric entry to the event codes returned by the event upload.

[test-data.zip](https://github.com/user-attachments/files/15874052/test-data.zip)

## Note
There are some issues still remaining with this implementation when it comes to importing data entries from the csv files.

- How should `code` be assigned to imported events?
- How should `code` of imported events be communicated to the user?
- What is the `status` of an imported event?
- What is the `duration` of an imported event?
- In order for the system to work properly I assume that the field `code` needs a uniqueness requirement?

### CODE REVIEW

**Comment by pdmnyberg** [comment]
Responding to some of the questions here:
- We ignore `code`, `status`, `duration` for the uploaded events for now

**Comment by pdmnyberg** [comment]
Additional questions that I have discovered:
- organizing institutions and connections to events are not properly imported at the moment
  - the data only includes two institutions and that does not cover the entire set available in event data
  - missing institutions are of course necessary in order to properly upload new events

**Comment by pdmnyberg** [comment]
This commit: https://github.com/elixir-europe-training/Training-Metrics-Database/pull/39/commits/10e9b055ec5e3d25cf188666b9be1a8e31744fca contains some adjustments to the models and the `load_data` script that allows for improve validation of the inputs. I would appreciate a discussion around how these things should be handled in a better way.

**Comment by pdmnyberg** [comment]
NOTE: Make sure old events can not be edited

**Comment by pdmnyberg** [comment]
Add second step to upload process, asking if a user wants to add to the metrics or replace the metrics for the given events. The second step should:
- List all referenced events
- Allow the user to select `delete` or `update` for each event
- Allow the user to `continue` or `cancel` the upload action

**Comment by pdmnyberg** [comment]
The only thing currently missing is the automatic import of institutions from ror_ids

**Review by brane007 — APPROVED** [review]

**Pull request merged**
