### PR TITLE
fix: add new domain as trusted origin

### LINKED ISSUE #32: login broken from new domain
**Describe the bug**

One cannot login from the new domain https://tmd.elixir-europe.org 

**To Reproduce**
- Go to: https://tmd.elixir-europe.org/login/
- With any user or just random credentials, try to sign in
- Press `Log in` => (403 `CSRF verification failed. Request aborted.`)

**Expected behavior**
- I should be able to sign in given that I use correct credentials. 
- I should be greeted with a sign in failure when trying to use 

**Additional context**

This issue was previously encountered and resolved https://github.com/elixir-europe-training/Training-Metrics-Database/pull/30/files

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This PR resolve #32 by adding the new domain to the trusted origin list.

### CODE REVIEW

**Comment by pdmnyberg** [comment]
I trust this will work. @mihai-sysbio have you tried it in production already or do you want me to test/approve it first?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio have you tried it in production already or do you want me to test/approve it first?

I've tried it already but it's worth double-checking.

**Comment by pdmnyberg** [comment]
> > @mihai-sysbio have you tried it in production already or do you want me to test/approve it first?
> 
> I've tried it already but it's worth double-checking.

Ok. I'll try to find some

**Comment by pdmnyberg** [comment]
I am having some trouble with unrelated issues when trying out the repo. For example we seem to be missing `django_countries==7.5.*` in `requirements.txt` and I am apparently too unfamiliar with the prod-environment since it is not completely represented in the repo right? I could try to setup my own nginx proxy but since it would't be the same I think I'll just accept this as working since I seem to be able to atleast get a proper failure message from the login page.

**Review by pdmnyberg — APPROVED** [review]
This seems to work but proved to be too much work to test locally atm. It would be nice to have a more complete local setup moving forward though,

**Pull request merged**
